const fs = require('fs');
var peg = require('pegjs');
// var Parser = require('parser'); // parser generated by pegjs --trace
var Tracer = require('pegjs-backtrace');

var grammar = fs.readFileSync('GIFT.pegjs', 'utf-8');
var parser = peg.generate(grammar);

// Make sure we got a filename on the command line.
if (process.argv.length < 3) {
    console.log('Usage: node ' + process.argv[1] + ' FILENAME');
    process.exit(1);
}

var filename = process.argv[2];
var text = fs.readFileSync(filename, 'utf8');
var tracer = new Tracer(text); // input text is required.

try {
    Parser.parse(text, { tracer: tracer });
} catch (e) {
    console.log(tracer.getBacktraceString());
}