const fs = require('fs');
var peg = require('pegjs');
// var Parser = require('./build/GIFT_parser'); // parser generated by pegjs --trace
var Tracer = require('pegjs-backtrace');

var grammar = fs.readFileSync('GIFT.pegjs', 'utf-8');
var Parser = peg.generate(grammar, { trace: true });

// Make sure we got a filename on the command line.
if (process.argv.length < 3) {
    console.log('Usage: node ' + process.argv[1] + ' FILENAME');
    process.exit(1);
}

var filename = process.argv[2];
var text = fs.readFileSync(filename, 'utf8');
// input text is required.
var tracer = new Tracer(text, {
    parent: null,
    hiddenPaths: [],
    useColor: true,
    showTrace: false,
    maxSourceLines: 6,
    maxPathLength: 72,
});

try {
    Parser.parse(text, { tracer: tracer });
} catch (e) {
    console.log(tracer.getBacktraceString());
}